name: sphinx
on: [push, pull_request]

jobs:
  build-and-delpoy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          apt-get install python3-sphinx
          pip install -r requirements.txt
          
      - name: Build Sphinx docs
        run: |
          cd docs/
          make html

      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build
