name: Run Python Tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the latest code from the repo
      - name: Checkout
        uses: actions/checkout@v2
        # Setup which version of Python to use
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
        # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .
        # Install pip package graphtoolbox
      - name: Install package
        run: |
          python -m pip install .
        # Run the tests
      - name: Run tests
        run: |
          pytest src/test/
